#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ ! -f  "$DOKKU_ROOT/HOSTNAME" ]]; then
    echo $(hostname -f) > $DOKKU_ROOT/HOSTNAME
fi

# temporary hack for https://github.com/progrium/dokku/issues/82
# redeploys all apps after a reboot
# FIXME: redeploy using systemd?
